ITB-1525 Update apis in Comments
invotra/api pull request #337
Opened 2021-04-13 16:14 UTC by klauselhai

- Get a comment by id
- Update a comment by id

2021-04-15 08:22 UTC, ParryLuke approved these changes
This PR looks good.

Can we add the attachments array to the POST/PUT endpoints? This should reference a file UUID created via the /files endpoint

2021-04-15 08:23 UTC, ParryLuke requested changes
Should've clicked 'request changes' rather than 'approve', see previous comment

2021-04-20 14:28 UTC, ParryLuke approved these changes

2021-05-19 10:15 UTC, sam-ludlow commented
closing PR replaced by https://github.com/invotra/api/pull/361

2021-05-19 10:15 UTC, closed without merging