INVGOV-13220 /like/{content_id} Node.js API endpoint
invotra/api pull request #353
Opened 2021-05-10 13:06 UTC by klauselhai

2021-05-13 16:30 UTC, ParryLuke requested changes

2021-05-13 16:30 UTC, ParryLuke commented on api.swagger.yaml
> +      description: 'Mark a piece of content/comment as like.'
'Like a piece of content/comment.'

2021-05-13 16:30 UTC, ParryLuke commented on api.swagger.yaml
> +          description: 'The content/comment was like successfully.'
'Liked the content/comment successfully.'

2021-05-13 16:30 UTC, ParryLuke commented on api.swagger.yaml
> +          description: 'The content/comment was not like due to malformed JSON.'
like -> liked

2021-05-13 16:30 UTC, ParryLuke commented on api.swagger.yaml
> +          description: 'User is not authorized to save a content/comment.'
"save a" -> "like this"

2021-05-13 16:30 UTC, ParryLuke commented on api.swagger.yaml
> +          description: 'The content/comment was not like due to Drupal validation failure or JSON schema validation failure.'
like -> liked

2021-05-13 16:30 UTC, ParryLuke commented on api.swagger.yaml
> +      description: 'Unsave a piece of content/comment.'
Unsave -> Unlike

2021-05-13 16:30 UTC, ParryLuke commented on api.swagger.yaml
> +        - like
"likes" category

2021-05-13 16:30 UTC, ParryLuke commented on api.swagger.yaml
> +          description: 'The content/comment was unlike.'
'Like removed successfully.'

2021-05-13 16:30 UTC, ParryLuke commented on api.swagger.yaml
> +          description: 'Could not unsave this content/comment due to malformed JSON.'
unsave -> unlike

2021-05-13 16:30 UTC, ParryLuke commented on api.swagger.yaml
> +          description: 'User is not authorized to unsave this content/comment.'
unlike

2021-05-13 16:30 UTC, ParryLuke commented on api.swagger.yaml
> +          description: 'The content/comment was not unlike due to Drupal validation failure or JSON schema validation failure.'
'The like could not be removed due to...'

2021-05-13 16:30 UTC, ParryLuke commented on api.swagger.yaml
> +      description: 'Check if a piece of content/comment is like or not.'
like -> liked

2021-05-13 16:30 UTC, ParryLuke commented on api.swagger.yaml
> +        - like
likes category

2021-05-13 16:30 UTC, ParryLuke commented on api.swagger.yaml
> +        current_user_like:
current_user_liked

2021-05-17 10:20 UTC, ParryLuke requested changes

2021-05-17 10:25 UTC, klauselhai commented on api.swagger.yaml
> +  '/like/{content_id}':
@ParryLuke Sure, Alright.

2021-05-17 13:35 UTC, ParryLuke requested changes
Can we change the POST to a PUT?

I think we'd need to do the same for /saved but I'll check now

2021-05-26 10:35 UTC, merged