INVGOV-13141 Update apis in Comments
invotra/api pull request #361
Opened 2021-05-17 16:58 UTC by klauselhai

https://io1dev.atlassian.net/browse/INVGOV-13141

2021-05-18 08:54 UTC, ParryLuke approved these changes

2021-05-19 10:33 UTC, sam-ludlow requested changes
attachments This should be an array of uuid objects: [ { uuid: 'wefewfwef' }, { uuid: 'erghergerg'} ]

2021-05-19 10:33 UTC, sam-ludlow commented on api.swagger.yaml
> +        attachments:
This should be an array of uuid objects: [ { uuid: 'wefewfwef' }, { uuid: 'erghergerg'} ]

2021-05-20 12:33 UTC, ParryLuke approved these changes

2021-05-20 12:57 UTC, sam-ludlow approved these changes

2022-01-11 15:23 UTC, MireilleHelle commented
Task closed as we’re now focusing on building only API gaps for which Invotra Consulting have a direct need.

2022-01-11 15:23 UTC, closed without merging