INVGOV-13228 /report/{content_id} Node.js API endpoint
invotra/api pull request #374
Opened 2021-06-07 08:43 UTC by klauselhai

2021-06-09 14:54 UTC, ParryLuke requested changes

2021-06-09 14:54 UTC, ParryLuke commented on api.swagger.yaml
> +      description: 'Unreport a piece of content/comment.'
Unreport a piece of content/comment.

->

Remove report flag from a piece of content/comment.

2021-06-09 14:54 UTC, ParryLuke commented on api.swagger.yaml
> +          description: 'Could not unreport this content/comment due to malformed JSON.'
Could not unreport this content/comment due to malformed JSON.

->

Could not remove report flag due to malformed JSON.

2021-06-09 14:54 UTC, ParryLuke commented on api.swagger.yaml
> +          description: 'User is not authorized to unreport this content/comment.'
User is not authorized to remove report flag.

2021-06-09 14:54 UTC, ParryLuke commented on api.swagger.yaml
> +      description: 'Check if a piece of content/comment is reported or not.'
Check if a piece of content/comment is reported or not.

->

Check if a piece of content/comment has been reported or not.

2021-06-09 14:54 UTC, ParryLuke commented on api.swagger.yaml
> +          default: false
Newline needed at end of file

2021-06-14 10:23 UTC, ParryLuke approved these changes

2022-01-11 15:29 UTC, MireilleHelle commented
Closing task as we’re now focusing on building only API gaps for which Invotra Consulting have a direct need.

2022-01-11 15:29 UTC, closed without merging