INVGOV-13236 Filter by group_uuid in /posts/list
invotra/api pull request #383
Opened 2021-06-24 10:19 UTC by klauselhai

https://io1dev.atlassian.net/browse/INVGOV-13236

2021-06-24 14:39 UTC, ParryLuke approved these changes

2021-06-29 14:14 UTC, ParryLuke requested changes

2021-06-29 14:14 UTC, ParryLuke commented on api.swagger.yaml
> +        - description: 'Filter by group UUID.'
This parameter should be for /posts/list

2022-01-11 15:32 UTC, MireilleHelle commented
Closing task as we’re now focusing on building only API gaps for which Invotra Consulting have a direct need.

2022-01-11 15:32 UTC, closed without merging