INVGOV-13430 POST /galleries missing
invotra/api pull request #384
Opened 2021-06-30 13:14 UTC by klauselhai

https://io1dev.atlassian.net/browse/INVGOV-13430

2021-07-27 15:00 UTC, sam-ludlow requested changes
Hello, gallery items are actually multi_media CTs.
On the GET we should include the whole multi_media object, on the PUT/POST it should be an object with just UUID (like with taxonomies).

GET:
gallery_items: [
  {
     title: 'sdfvdsf',
     multi_media: { uuid, title, body ... } << full object
  }
]

POST/PUT:
gallery_items: [
  {
     title: 'sdfvdsf',
     multi_media: { uuid: '345345345345' } << just UUID
  }
]

2021-07-28 13:40 UTC, klauselhai commented
> Hello, gallery items are actually multi_media CTs.
> On the GET we should include the whole multi_media object, on the PUT/POST it should be an object with just UUID (like with taxonomies).
> 
> GET:
> gallery_items: [
> {
> title: 'sdfvdsf',
> multi_media: { uuid, title, body ... } << full object
> }
> ]
> 
> POST/PUT:
> gallery_items: [
> {
> title: 'sdfvdsf',
> multi_media: { uuid: '345345345345' } << just UUID
> }
> ]

Hi @sam-ludlow 
in example when sending data to drupal, I don’t see multi_media field in this ticket https://io1dev.atlassian.net/browse/INVGOV-13576
or backend guys are missing that field?

2021-07-28 13:50 UTC, sam-ludlow commented
Hello, it doesnt matter what its called on drupal services.

We a just calling it multi_media on the API because thats what it is.

Cheers

2021-08-25 10:07 UTC, sam-ludlow requested changes

2021-08-25 10:07 UTC, sam-ludlow commented on api.swagger.yaml
> +            gallery_items:
Please include a description

2021-08-25 10:07 UTC, sam-ludlow commented on api.swagger.yaml
> +              uuid:
Please include a description & example (see other UUIDs)

2021-09-01 16:23 UTC, sam-ludlow approved these changes
Looks good

2021-10-06 10:12 UTC, merged