INVGOV-13414 /site_sections/{site_section_id}/widgets
invotra/api pull request #386
Opened 2021-07-01 16:31 UTC by klauselhai

https://io1dev.atlassian.net/browse/INVGOV-13414

2021-07-07 09:54 UTC, ParryLuke approved these changes

2021-07-07 09:54 UTC, ParryLuke commented on api.swagger.yaml
> +        - widget_uuid
Newline needed

2021-07-07 09:55 UTC, ParryLuke requested changes

2021-07-07 09:55 UTC, ParryLuke commented on api.swagger.yaml
> +      required:
Newline needed at bottom of file

2022-01-11 15:42 UTC, MireilleHelle commented
Closing task as we’re now focusing on building only API gaps for which Invotra Consulting have a direct need.

2022-01-11 15:42 UTC, closed without merging