INVGOV-13598 API feeds facets Akagera data does not match swagger
invotra/api pull request #394
Opened 2021-07-07 11:00 UTC by sam-ludlow

https://io1dev.atlassian.net/browse/INVGOV-13598

2021-07-07 11:14 UTC, ParryLuke approved these changes

2021-07-07 11:15 UTC, ParryLuke requested changes

2021-07-07 11:15 UTC, ParryLuke commented on api.swagger.yaml
> +                      - ''
Has this been double checked with product? It could be a data bug?

2021-07-27 15:53 UTC, sam-ludlow commented
Luke is not wrong, closing PR, it shouldn't do this, no situation where there isn't a topic.

2021-07-27 15:53 UTC, closed without merging