INVGOV-13632 /notifications add more fields for client
invotra/api pull request #412
Opened 2021-08-05 12:24 UTC by klauselhai

2021-08-19 10:40 UTC, sam-ludlow requested changes
Think we should use the existing term "target", all 3 types can be put together.

target: {
    target_type: 'node / comment / user' (enum)
    target_entity: {...} (node / comment / user' object)
}

Have a look in swagger at "discriminator". There needs to be a way for schema validation to determine what the type is.

I think we may have to create 3 schemas for each type that just have the type and ref to schema e.g:

{
    target_type: 'user' (use an enum with a single value)
    target_entity: $ref: '#/components/schemas/user-schema'
}

2021-08-25 10:33 UTC, sam-ludlow requested changes

2021-08-25 10:33 UTC, sam-ludlow commented on api.swagger.yaml
> +        target:
Have a look in swagger at "discriminator". There needs to be a way for schema validation to determine what the type is.

2021-08-25 10:45 UTC, sam-ludlow requested changes
We need facets and filters on the notifications EP see https://io1dev.atlassian.net/browse/INVGOV-13632?focusedCommentId=302417

2022-01-11 16:08 UTC, MireilleHelle commented
Closing task as we’re now focusing on building only API gaps for which Invotra Consulting have a direct need.

2022-01-11 16:08 UTC, closed without merging