INVGOV-14001 /job_roles/merge Node.js API endpoint
invotra/api pull request #440
Opened 2021-10-01 07:40 UTC by klauselhai

https://io1dev.atlassian.net/browse/INVGOV-14001

2021-10-01 10:27 UTC, sam-ludlow requested changes

2021-10-01 10:27 UTC, sam-ludlow commented on api.swagger.yaml
> +  '/job_roles/merge':
I think we should do:

PUT ​/job_roles​/{job_role_id}/merge
body { merge_uuids[] }

2021-10-01 10:27 UTC, sam-ludlow commented on api.swagger.yaml
> +      description: Provision a new job role.
Bad description

2021-10-04 14:25 UTC, sam-ludlow approved these changes
Looks good

2022-01-11 15:37 UTC, MireilleHelle commented
Closing task as we’re now focusing on building only API gaps for which Invotra Consulting have a direct need.

2022-01-11 15:37 UTC, closed without merging